import { sqliteTable, text, real, integer, primaryKey } from 'drizzle-orm/sqlite-core';

export const records = sqliteTable('records', {
  id: integer('id').primaryKey(),
  fecha: text('fecha').notNull(),
  hora: text('hora').notNull(),
  nombreOperador: text('nombre_operador').notNull(),
  caudal: real('caudal').notNull(),
  turbidezAguaCruda: real('turbidez_agua_cruda'),
  phAguaCruda: real('ph_agua_cruda'),
  temperatura: real('temperatura'),
  turbidezAguaClarificada: real('turbidez_agua_clarificada'),
  phAguaClarificada: real('ph_agua_clarificada'),
  cloro: real('cloro'),
  pac_ml_min: real('pac_ml_min'),
  pac_ppm: real('pac_ppm'),
  soda_ml_min: real('soda_ml_min'),
  soda_ppm: real('soda_ppm'),
  ebap_b1: text('ebap_b1'),
  ebap_b2: text('ebap_b2'),
  ebap_b3: text('ebap_b3'),
  ebap_b4: text('ebap_b4'),
  ebac_b1: text('ebac_b1'),
  ebac_b2: text('ebac_b2'),
  ebac_b3: text('ebac_b3'),
  ebac_b4: text('ebac_b4'),
  filtros_f1: text('filtros_f1'),
  filtros_f2: text('filtros_f2'),
  filtros_f3: text('filtros_f3'),
  filtros_f4: text('filtros_f4'),
  filtros_f5: text('filtros_f5'),
  filtros_f6: text('filtros_f6'),
  filtros_f7: text('filtros_f7'),
  filtros_f8: text('filtros_f8'),
  observaciones: text('observaciones'),
  timestamp: integer('timestamp', { mode: 'timestamp' }).notNull(),
});
