CREATE TABLE `records` (
	`id` integer PRIMARY KEY NOT NULL,
	`fecha` text NOT NULL,
	`hora` text NOT NULL,
	`nombre_operador` text NOT NULL,
	`caudal` real NOT NULL,
	`turbidez_agua_cruda` real,
	`ph_agua_cruda` real,
	`temperatura` real,
	`turbidez_agua_clarificada` real,
	`ph_agua_clarificada` real,
	`cloro` real,
	`pac_ml_min` real,
	`pac_ppm` real,
	`soda_ml_min` real,
	`soda_ppm` real,
	`ebap_b1` text,
	`ebap_b2` text,
	`ebap_b3` text,
	`ebap_b4` text,
	`ebac_b1` text,
	`ebac_b2` text,
	`ebac_b3` text,
	`ebac_b4` text,
	`filtros_f1` text,
	`filtros_f2` text,
	`filtros_f3` text,
	`filtros_f4` text,
	`filtros_f5` text,
	`filtros_f6` text,
	`filtros_f7` text,
	`filtros_f8` text,
	`observaciones` text,
	`timestamp` integer NOT NULL
);
